"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-change-this-in-production-2026'
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'jazzmin',                    # ← Thêm dòng này, phải ở trên cùng
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps của chúng ta
    'products',
    'crm',
    'transactions',
    'dashboard',

    # Packages
    'channels',
    'rest_framework',
    'django_htmx',
    'guardian',

    'django.contrib.sites',           # Bắt buộc cho allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',          # nếu không dùng social thì vẫn cần

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'
ASGI_APPLICATION = 'core.asgi.application'

# === REAL-TIME CHANNELS ===
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
}]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# === Allauth Settings ===
SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'   # 'mandatory' nếu muốn bắt buộc xác thực email
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # default
    'guardian.backends.ObjectPermissionBackend',  # cho object-level
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Thêm vào cuối settings.py
ACCOUNT_FORMS = {
    'signup': 'crm.forms.CustomSignupForm',
}

JAZZMIN_SETTINGS = {
    "site_title": "ERP Bất Động Sản",
    "site_header": "Quản Trị BĐS",
    "site_brand": "RealEstate ERP",
    "site_logo": None,                    # Bạn có thể thêm logo sau
    "welcome_sign": "Chào mừng đến với Hệ thống Quản trị Nội bộ",
    
    # Theme
    "theme": "darkly",                    # hoặc "flatly", "cyborg", "solar", "superhero"...
    "dark_mode_theme": "darkly",
    
    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index"},
        {"name": "Website", "url": "/", "new_window": True},
    ],
    
    "show_sidebar": True,
    "navigation_expanded": True,
    
    "icons": {
        "auth.User": "fas fa-users",
        "auth.Group": "fas fa-users-cog",
        "products.Project": "fas fa-building",
        "products.Product": "fas fa-home",
        "crm.Customer": "fas fa-user-tie",
        "transactions.Transaction": "fas fa-file-contract",
    },
    
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": True,              # Cho phép bạn tùy chỉnh theme trực tiếp trong admin
}