# Generated by Django 5.1 on 2026-03-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã căn/lô')),
                ('status', models.CharField(choices=[('available', '🟢 Trống'), ('reserved', '🟡 Cọc'), ('sold', '🔴 Đã bán')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.project')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
            },
        ),
    ]
